save_checkpoint_steps: 500
keep_checkpoint: 1
seed: 3435
train_steps: 50000
valid_steps: 500
report_every: 500

encoder_type: brnn
word_vec_size: 512
rnn_size: 512
layers: 1

optim: adagrad
learning_rate: 0.15
adagrad_accumulator_init: 0.1
max_grad_norm: 2

batch_size: 128
dropout: 0.0

global_attention: mlp
reuse_copy_attn: 'true'
bridge: 'true'
early_stopping: 10
