
BATCH_SIZE: 128
BEAM_WIDTH: 0
BIRNN: True
CSV_BUFFER_SIZE: 104857600
DECODER_SIZE: 320
EMBEDDINGS_DROPOUT_KEEP_PROB: 0.75
EMBEDDINGS_SIZE: 128
MAX_CONTEXTS: 200
MAX_NAME_PARTS: 5
MAX_PATH_LENGTH: 9
MAX_TARGET_PARTS: 6
NUM_DECODER_LAYERS: 1
NUM_EPOCHS: 3000
PATIENCE: 10
RANDOM_CONTEXTS: True
READER_NUM_PARALLEL_BATCHES: 1
RNN_DROPOUT_KEEP_PROB: 0.5
RNN_SIZE: 256
SAVE_EVERY_EPOCHS: 1
SHUFFLE_BUFFER_SIZE: 10000
SUBTOKENS_VOCAB_MAX_SIZE: 190000
TARGET_VOCAB_MAX_SIZE: 27000
TEST_BATCH_SIZE: 64
USE_MOMENTUM: True